nxp-imx7: introduce MACHINE_SOCARCH for i.MX7 bsp
Issue: LINUXEXEC-33431

When compiling the SATO image, a compilation error may occur due to an
incorrect definition of 'MACHINE_SOCARCH'. To avoid such compilation
issues, introduce the definition of MACHINE_SOCARCH for i.MX7.

ERROR: Directory name /build/tmp-glibc/work/${MACHINE_SOCARCH}-wrs-linux-gnueabi/pulseaudio/17.0/temp contains unexpanded bitbake variable. This may cause build failures and WORKDIR polution.
ERROR: Task (layers/oe-core/meta/recipes-multimedia/pulseaudio/pulseaudio_17.0.bb:do_recipe_qa) failed with exit code '1'

Signed-off-by: Ruiqiang Hao <Ruiqiang.Hao@windriver.com>